version: '3'
services:
    redis:
        container_name: redis
        image: redis:latest
        expose:
            - 6379

    collector:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - redis
        depends_on:
            - redis

