default:
  DEBUG: true
  COLLECTORS_PATHS:
    - opulence.collectors.collectors
  CELERY_WORKER:
    broker_url: redis://localhost/0
    result_backend: redis://localhost/0

development:
  DEBUG: true

production:
  DEBUG: false
  CELERY_WORKER:
    broker_url: redis://redis/0
    result_backend: redis://redis/0

