log:
  file: opulence.log
  debug: True



collectors:
    paths:
        - opulence.collectors.collectors
collectors_service:
    worker:
        broker_url: redis://redis/0
        result_backend: redis://redis/0
